language: python
python:
  - "2.7"
install:
  - pip install fontmake
script:
  - fontmake -u src/light.ufo src/bold.ufo src/mini.ufo src/serif.ufo 
  - zip -r master_otf.zip master_otf
  - curl --progress-bar --upload-file master_otf.zip "https://transfer.sh/construction-fonts.zip" -o link && cat link && echo
